apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dlc6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dlc6
    app.kubernetes.io/part-of: tkrw-pr712-0075-0032-app
  name: devfile-sample-dlc6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dlc6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dlc6
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-dlc6@sha256:7f63f8a810323acd595b538b02ffed6f360fbac48a16da1053474ea2a169d870
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
